[package]
name = "godot-rapier"
version = "0.7.0"
edition = "2021"
license = "MIT"
rust-version = "1.81"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["single-dim3", "serde-serialize", "parallel", "enhanced-determinism"]
dim2 = []
dim3 = []
single = []
double = []
# TODO add feature for "glam/libm"
enhanced-determinism = ["rapier2d/enhanced-determinism", "rapier2d-f64/enhanced-determinism", "rapier3d/enhanced-determinism", "rapier3d-f64/enhanced-determinism", "godot/enchanced-determinism"]
serde-serialize = ["serde", "hashbrown/serde", "bincode", "serde_json", "typetag", "godot/serde", "rapier2d/serde-serialize", "rapier2d-f64/serde-serialize", "rapier3d/serde-serialize", "rapier3d-f64/serde-serialize" ]
simd-stable = ["rapier2d/simd-stable", "rapier2d-f64/simd-stable", "rapier3d/simd-stable", "rapier3d-f64/simd-stable"]
simd-nightly = ["rapier2d/simd-nightly", "rapier2d-f64/simd-nightly", "rapier3d/simd-nightly", "rapier3d-f64/simd-nightly"]
wasm-bindgen = ["rapier2d/wasm-bindgen", "rapier2d-f64/wasm-bindgen", "rapier3d/wasm-bindgen", "rapier3d-f64/wasm-bindgen"]
#parallel = ["rapier2d/parallel", "rapier2d-f64/parallel", "rapier3d/parallel", "rapier3d-f64/parallel"]
parallel = []
experimental-wasm = ["godot/experimental-wasm", "godot/lazy-function-tables"]
single-dim2 = ["single", "dim2", "rapier2d", "salva2d"]
double-dim2 = ["double", "dim2", "rapier2d-f64", "salva2d"]
single-dim3 = ["single", "dim3", "rapier3d", "salva3d"]
double-dim3 = ["double", "dim3", "rapier3d-f64", "salva3d"]

[dependencies]
bincode = { version = "1", optional = true }
hashbrown = { version = "0.14" }

godot = { git = "https://github.com/ughuuu/gdext", branch = "make-stuff-serializable", features=["api-4-2"] }
#godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features=["api-4-2"] }

rapier2d = { version = "0.21", optional = true }
rapier2d-f64 = { version = "0.21", optional = true}
rapier3d = { version = "0.21", optional = true}
rapier3d-f64 = { version = "0.21", optional = true}
salva2d = { git = "https://github.com/dimforge/salva", branch = "master", features = ["rapier"], optional = true }
salva3d = { git = "https://github.com/dimforge/salva", branch = "master", features = ["rapier"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
typetag = { version = "0.2", optional = true }

[patch.crates-io]
rapier2d = {git = "https://github.com/dimforge/rapier", branch = "master"}
rapier2d-f64 = {git = "https://github.com/dimforge/rapier", branch = "master"}
parry2d = {git = "https://github.com/dimforge/parry", branch = "master"}
parry2d-f64 = {git = "https://github.com/dimforge/parry", branch = "master"}

rapier3d = {git = "https://github.com/dimforge/rapier", branch = "master"}
rapier3d-f64 = {git = "https://github.com/dimforge/rapier", branch = "master"}
parry3d = {git = "https://github.com/dimforge/parry", branch = "master"}
parry3d-f64 = {git = "https://github.com/dimforge/parry", branch = "master"}

[profile.release]
opt-level = 3
debug = 2
strip = "debuginfo"
lto = "fat"
panic = 'unwind'
codegen-units = 1

[profile.dev]
opt-level = 1

[package.metadata.docs.rs]
license-file = "../LICENSE"
